// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "k2c_dense.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic k2c_dense::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic k2c_dense::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> k2c_dense::ap_ST_fsm_state1 = "1";
const sc_lv<9> k2c_dense::ap_ST_fsm_state2 = "10";
const sc_lv<9> k2c_dense::ap_ST_fsm_state3 = "100";
const sc_lv<9> k2c_dense::ap_ST_fsm_state4 = "1000";
const sc_lv<9> k2c_dense::ap_ST_fsm_state5 = "10000";
const sc_lv<9> k2c_dense::ap_ST_fsm_state6 = "100000";
const sc_lv<9> k2c_dense::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> k2c_dense::ap_ST_fsm_pp0_stage0 = "10000000";
const sc_lv<9> k2c_dense::ap_ST_fsm_state10 = "100000000";
const bool k2c_dense::ap_const_boolean_1 = true;
const sc_lv<32> k2c_dense::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> k2c_dense::ap_const_lv1_0 = "0";
const sc_lv<1> k2c_dense::ap_const_lv1_1 = "1";
const sc_lv<32> k2c_dense::ap_const_lv32_2 = "10";
const sc_lv<32> k2c_dense::ap_const_lv32_3 = "11";
const sc_lv<32> k2c_dense::ap_const_lv32_5 = "101";
const sc_lv<32> k2c_dense::ap_const_lv32_6 = "110";
const sc_lv<32> k2c_dense::ap_const_lv32_7 = "111";
const bool k2c_dense::ap_const_boolean_0 = false;
const sc_lv<32> k2c_dense::ap_const_lv32_8 = "1000";
const sc_lv<6> k2c_dense::ap_const_lv6_0 = "000000";
const sc_lv<32> k2c_dense::ap_const_lv32_1 = "1";
const sc_lv<128> k2c_dense::ap_const_lv128_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> k2c_dense::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> k2c_dense::ap_const_lv32_4 = "100";
const sc_lv<7> k2c_dense::ap_const_lv7_0 = "0000000";
const sc_lv<64> k2c_dense::ap_const_lv64_1 = "1";
const sc_lv<64> k2c_dense::ap_const_lv64_3 = "11";
const sc_lv<64> k2c_dense::ap_const_lv64_FFFFFFFFFFFFFFFF = "1111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> k2c_dense::ap_const_lv32_3F = "111111";
const sc_lv<63> k2c_dense::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<6> k2c_dense::ap_const_lv6_24 = "100100";
const sc_lv<128> k2c_dense::ap_const_lv128_lc_2 = "1";
const sc_lv<7> k2c_dense::ap_const_lv7_64 = "1100100";
const sc_lv<7> k2c_dense::ap_const_lv7_1 = "1";

k2c_dense::k2c_dense(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_k2c_dot_1_fu_270 = new k2c_dot_1("grp_k2c_dot_1_fu_270");
    grp_k2c_dot_1_fu_270->ap_clk(ap_clk);
    grp_k2c_dot_1_fu_270->ap_rst(ap_rst);
    grp_k2c_dot_1_fu_270->ap_start(grp_k2c_dot_1_fu_270_ap_start);
    grp_k2c_dot_1_fu_270->ap_done(grp_k2c_dot_1_fu_270_ap_done);
    grp_k2c_dot_1_fu_270->ap_idle(grp_k2c_dot_1_fu_270_ap_idle);
    grp_k2c_dot_1_fu_270->ap_ready(grp_k2c_dot_1_fu_270_ap_ready);
    grp_k2c_dot_1_fu_270->C_array_address0(grp_k2c_dot_1_fu_270_C_array_address0);
    grp_k2c_dot_1_fu_270->C_array_ce0(grp_k2c_dot_1_fu_270_C_array_ce0);
    grp_k2c_dot_1_fu_270->C_array_we0(grp_k2c_dot_1_fu_270_C_array_we0);
    grp_k2c_dot_1_fu_270->C_array_d0(grp_k2c_dot_1_fu_270_C_array_d0);
    grp_k2c_dot_1_fu_270->Ar_array_address0(grp_k2c_dot_1_fu_270_Ar_array_address0);
    grp_k2c_dot_1_fu_270->Ar_array_ce0(grp_k2c_dot_1_fu_270_Ar_array_ce0);
    grp_k2c_dot_1_fu_270->Ar_array_q0(input_array_q0);
    grp_k2c_dot_1_fu_270->Ar_ndim_read(input_ndim_read);
    grp_k2c_dot_1_fu_270->Ar_numel_read(input_numel_read);
    grp_k2c_dot_1_fu_270->Ar_shape_address0(grp_k2c_dot_1_fu_270_Ar_shape_address0);
    grp_k2c_dot_1_fu_270->Ar_shape_ce0(grp_k2c_dot_1_fu_270_Ar_shape_ce0);
    grp_k2c_dot_1_fu_270->Ar_shape_q0(input_shape_q0);
    grp_k2c_dot_1_fu_270->B_array_address0(grp_k2c_dot_1_fu_270_B_array_address0);
    grp_k2c_dot_1_fu_270->B_array_ce0(grp_k2c_dot_1_fu_270_B_array_ce0);
    grp_k2c_dot_1_fu_270->B_array_q0(kernel_array_q0);
    grp_k2c_dot_1_fu_270->B_shape_address0(grp_k2c_dot_1_fu_270_B_shape_address0);
    grp_k2c_dot_1_fu_270->B_shape_ce0(grp_k2c_dot_1_fu_270_B_shape_ce0);
    grp_k2c_dot_1_fu_270->B_shape_q0(kernel_shape_q0);
    grp_k2c_dot_1_fu_270->p_read4(tmp_s_reg_550);
    grp_k2c_dot_1_fu_270->fwork_address0(grp_k2c_dot_1_fu_270_fwork_address0);
    grp_k2c_dot_1_fu_270->fwork_ce0(grp_k2c_dot_1_fu_270_fwork_ce0);
    grp_k2c_dot_1_fu_270->fwork_we0(grp_k2c_dot_1_fu_270_fwork_we0);
    grp_k2c_dot_1_fu_270->fwork_d0(grp_k2c_dot_1_fu_270_fwork_d0);
    grp_k2c_dot_1_fu_270->fwork_q0(fwork_q0);
    grp_k2c_dot_1_fu_270->fwork_address1(grp_k2c_dot_1_fu_270_fwork_address1);
    grp_k2c_dot_1_fu_270->fwork_ce1(grp_k2c_dot_1_fu_270_fwork_ce1);
    grp_k2c_dot_1_fu_270->fwork_q1(fwork_q1);
    face_classifier_cbkb_U30 = new face_classifier_cbkb<1,1,32,32,32>("face_classifier_cbkb_U30");
    face_classifier_cbkb_U30->din0(grp_fu_291_p0);
    face_classifier_cbkb_U30->din1(grp_fu_291_p1);
    face_classifier_cbkb_U30->dout(grp_fu_291_p2);
    face_classifier_ccud_U31 = new face_classifier_ccud<1,1,32,32,32>("face_classifier_ccud_U31");
    face_classifier_ccud_U31->din0(input_array_q0);
    face_classifier_ccud_U31->din1(kernel_array_q0);
    face_classifier_ccud_U31->dout(tmp_47_fu_299_p2);
    face_classifier_chbi_U32 = new face_classifier_chbi<1,1,13,13,13,13>("face_classifier_chbi_U32");
    face_classifier_chbi_U32->din0(tmp_75_reg_654);
    face_classifier_chbi_U32->din1(tmp_77_fu_388_p1);
    face_classifier_chbi_U32->din2(grp_fu_523_p2);
    face_classifier_chbi_U32->dout(grp_fu_523_p3);
    face_classifier_cg8j_U33 = new face_classifier_cg8j<1,1,13,13,13>("face_classifier_cg8j_U33");
    face_classifier_cg8j_U33->din0(tmp_76_reg_664);
    face_classifier_cg8j_U33->din1(tmp_77_fu_388_p1);
    face_classifier_cg8j_U33->dout(inneridx_mid2_fu_531_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state8);
    sensitive << ( exitcond_fu_474_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_flatten_fu_349_p2 );
    sensitive << ( tmp_i_fu_343_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_flatten_fu_349_p2 );
    sensitive << ( tmp_i_fu_343_p2 );

    SC_METHOD(thread_bias_array_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_mid2_fu_365_p3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_i_cast1_fu_404_p1 );

    SC_METHOD(thread_bias_array_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_bound_fu_468_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( bound_fu_468_p00 );

    SC_METHOD(thread_bound_fu_468_p00);
    sensitive << ( kernel_shape_q0 );

    SC_METHOD(thread_bound_fu_468_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( bound_fu_468_p10 );

    SC_METHOD(thread_bound_fu_468_p10);
    sensitive << ( outrows2_fu_441_p3 );

    SC_METHOD(thread_bound_fu_468_p2);
    sensitive << ( bound_fu_468_p0 );
    sensitive << ( bound_fu_468_p1 );

    SC_METHOD(thread_exitcond16_fu_360_p2);
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_flatten_fu_349_p2 );
    sensitive << ( outcols_reg_644 );
    sensitive << ( j_reg_227 );

    SC_METHOD(thread_exitcond_flatten_fu_349_p2);
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( bound_reg_669 );
    sensitive << ( indvar_flatten_reg_205 );

    SC_METHOD(thread_exitcond_fu_474_p2);
    sensitive << ( k_reg_259 );
    sensitive << ( innerdim_reg_659 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_i_fu_413_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_i_reg_238 );

    SC_METHOD(thread_fwork_address0);
    sensitive << ( grp_k2c_dot_1_fu_270_fwork_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_fwork_address1);
    sensitive << ( grp_k2c_dot_1_fu_270_fwork_address1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_fwork_ce0);
    sensitive << ( grp_k2c_dot_1_fu_270_fwork_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_fwork_ce1);
    sensitive << ( grp_k2c_dot_1_fu_270_fwork_ce1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_fwork_d0);
    sensitive << ( grp_k2c_dot_1_fu_270_fwork_d0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_fwork_we0);
    sensitive << ( grp_k2c_dot_1_fu_270_fwork_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_fu_291_p0);
    sensitive << ( output_array_q0 );
    sensitive << ( tmp_43_reg_249 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_291_p1);
    sensitive << ( bias_array_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_47_fu_299_p2 );

    SC_METHOD(thread_grp_fu_523_p2);
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_mid2_fu_365_p3 );
    sensitive << ( exitcond_flatten_fu_349_p2 );

    SC_METHOD(thread_grp_k2c_dot_1_fu_270_ap_start);
    sensitive << ( grp_k2c_dot_1_fu_270_ap_start_reg );

    SC_METHOD(thread_i_41_fu_374_p2);
    sensitive << ( i_reg_216 );

    SC_METHOD(thread_i_i_cast7_fu_335_p1);
    sensitive << ( i_i_reg_193 );

    SC_METHOD(thread_i_i_cast_fu_339_p1);
    sensitive << ( i_i_cast7_fu_335_p1 );

    SC_METHOD(thread_i_s_fu_435_p2);
    sensitive << ( i_i_reg_193 );

    SC_METHOD(thread_icmp_fu_329_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );
    sensitive << ( tmp_73_fu_319_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_354_p2);
    sensitive << ( indvar_flatten_reg_205 );

    SC_METHOD(thread_input_array_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_k2c_dot_1_fu_270_Ar_array_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_46_cast_fu_498_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_input_array_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_k2c_dot_1_fu_270_Ar_array_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_shape_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );
    sensitive << ( grp_k2c_dot_1_fu_270_Ar_shape_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_shape_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );
    sensitive << ( grp_k2c_dot_1_fu_270_Ar_shape_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_15_fu_419_p2);
    sensitive << ( j_i_reg_238 );

    SC_METHOD(thread_j_2_fu_518_p2);
    sensitive << ( j_mid2_reg_591 );

    SC_METHOD(thread_j_i_cast1_fu_404_p1);
    sensitive << ( j_i_reg_238 );

    SC_METHOD(thread_j_i_cast_fu_409_p1);
    sensitive << ( j_i_reg_238 );

    SC_METHOD(thread_j_mid2_fu_365_p3);
    sensitive << ( j_reg_227 );
    sensitive << ( exitcond16_fu_360_p2 );

    SC_METHOD(thread_k_4_fu_479_p2);
    sensitive << ( k_reg_259 );

    SC_METHOD(thread_kernel_array_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_k2c_dot_1_fu_270_B_array_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_48_cast_fu_513_p1 );

    SC_METHOD(thread_kernel_array_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_k2c_dot_1_fu_270_B_array_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_kernel_shape_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );
    sensitive << ( grp_k2c_dot_1_fu_270_B_shape_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_kernel_shape_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );

    SC_METHOD(thread_kernel_shape_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );
    sensitive << ( grp_k2c_dot_1_fu_270_B_shape_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_kernel_shape_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );

    SC_METHOD(thread_output_array_address0);
    sensitive << ( output_array_addr_reg_616 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( output_array_addr_2_reg_634 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_k2c_dot_1_fu_270_C_array_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_i_cast_fu_430_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_array_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_k2c_dot_1_fu_270_C_array_ce0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_array_d0);
    sensitive << ( bias_array_q0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( grp_fu_291_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_k2c_dot_1_fu_270_C_array_d0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_array_we0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_reg_679 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_k2c_dot_1_fu_270_C_array_we0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_outrowidx_mid2_v_v_fu_380_p3);
    sensitive << ( i_reg_216 );
    sensitive << ( exitcond16_fu_360_p2 );
    sensitive << ( i_41_fu_374_p2 );

    SC_METHOD(thread_outrows2_fu_441_p3);
    sensitive << ( input_shape_q0 );
    sensitive << ( icmp_reg_555 );

    SC_METHOD(thread_tmp_44_cast_fu_400_p1);
    sensitive << ( grp_fu_523_p3 );

    SC_METHOD(thread_tmp_44_fu_493_p2);
    sensitive << ( inneridx_mid2_reg_601 );
    sensitive << ( tmp_81_fu_489_p1 );

    SC_METHOD(thread_tmp_45_fu_503_p2);
    sensitive << ( tmp_74_reg_649 );
    sensitive << ( tmp_80_fu_485_p1 );

    SC_METHOD(thread_tmp_46_cast_fu_498_p1);
    sensitive << ( tmp_44_fu_493_p2 );

    SC_METHOD(thread_tmp_46_fu_508_p2);
    sensitive << ( tmp_78_reg_606 );
    sensitive << ( tmp_45_fu_503_p2 );

    SC_METHOD(thread_tmp_48_cast_fu_513_p1);
    sensitive << ( tmp_46_fu_508_p2 );

    SC_METHOD(thread_tmp_73_fu_319_p4);
    sensitive << ( input_ndim_read );

    SC_METHOD(thread_tmp_74_fu_448_p1);
    sensitive << ( kernel_shape_q0 );

    SC_METHOD(thread_tmp_75_fu_452_p1);
    sensitive << ( kernel_shape_q0 );

    SC_METHOD(thread_tmp_76_fu_456_p1);
    sensitive << ( kernel_shape_q1 );

    SC_METHOD(thread_tmp_77_fu_388_p1);
    sensitive << ( outrowidx_mid2_v_v_fu_380_p3 );

    SC_METHOD(thread_tmp_78_fu_392_p1);
    sensitive << ( j_mid2_fu_365_p3 );

    SC_METHOD(thread_tmp_80_fu_485_p1);
    sensitive << ( k_reg_259 );

    SC_METHOD(thread_tmp_81_fu_489_p1);
    sensitive << ( k_reg_259 );

    SC_METHOD(thread_tmp_fu_306_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_ndim_read );

    SC_METHOD(thread_tmp_i_43_fu_425_p2);
    sensitive << ( i_i_cast_reg_575 );
    sensitive << ( j_i_cast_fu_409_p1 );

    SC_METHOD(thread_tmp_i_cast_fu_430_p1);
    sensitive << ( tmp_i_43_fu_425_p2 );

    SC_METHOD(thread_tmp_i_fu_343_p2);
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_i_reg_193 );

    SC_METHOD(thread_tmp_s_fu_312_p2);
    sensitive << ( input_ndim_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_306_p2 );
    sensitive << ( tmp_reg_546 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_flatten_fu_349_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_i_fu_413_p2 );
    sensitive << ( exitcond_fu_474_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( grp_k2c_dot_1_fu_270_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_fu_343_p2 );

    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    grp_k2c_dot_1_fu_270_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "k2c_dense_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_array_address0, "(port)output_array_address0");
    sc_trace(mVcdFile, output_array_ce0, "(port)output_array_ce0");
    sc_trace(mVcdFile, output_array_we0, "(port)output_array_we0");
    sc_trace(mVcdFile, output_array_d0, "(port)output_array_d0");
    sc_trace(mVcdFile, output_array_q0, "(port)output_array_q0");
    sc_trace(mVcdFile, input_array_address0, "(port)input_array_address0");
    sc_trace(mVcdFile, input_array_ce0, "(port)input_array_ce0");
    sc_trace(mVcdFile, input_array_q0, "(port)input_array_q0");
    sc_trace(mVcdFile, input_ndim_read, "(port)input_ndim_read");
    sc_trace(mVcdFile, input_numel_read, "(port)input_numel_read");
    sc_trace(mVcdFile, input_shape_address0, "(port)input_shape_address0");
    sc_trace(mVcdFile, input_shape_ce0, "(port)input_shape_ce0");
    sc_trace(mVcdFile, input_shape_q0, "(port)input_shape_q0");
    sc_trace(mVcdFile, kernel_array_address0, "(port)kernel_array_address0");
    sc_trace(mVcdFile, kernel_array_ce0, "(port)kernel_array_ce0");
    sc_trace(mVcdFile, kernel_array_q0, "(port)kernel_array_q0");
    sc_trace(mVcdFile, kernel_shape_address0, "(port)kernel_shape_address0");
    sc_trace(mVcdFile, kernel_shape_ce0, "(port)kernel_shape_ce0");
    sc_trace(mVcdFile, kernel_shape_q0, "(port)kernel_shape_q0");
    sc_trace(mVcdFile, kernel_shape_address1, "(port)kernel_shape_address1");
    sc_trace(mVcdFile, kernel_shape_ce1, "(port)kernel_shape_ce1");
    sc_trace(mVcdFile, kernel_shape_q1, "(port)kernel_shape_q1");
    sc_trace(mVcdFile, bias_array_address0, "(port)bias_array_address0");
    sc_trace(mVcdFile, bias_array_ce0, "(port)bias_array_ce0");
    sc_trace(mVcdFile, bias_array_q0, "(port)bias_array_q0");
    sc_trace(mVcdFile, fwork_address0, "(port)fwork_address0");
    sc_trace(mVcdFile, fwork_ce0, "(port)fwork_ce0");
    sc_trace(mVcdFile, fwork_we0, "(port)fwork_we0");
    sc_trace(mVcdFile, fwork_d0, "(port)fwork_d0");
    sc_trace(mVcdFile, fwork_q0, "(port)fwork_q0");
    sc_trace(mVcdFile, fwork_address1, "(port)fwork_address1");
    sc_trace(mVcdFile, fwork_ce1, "(port)fwork_ce1");
    sc_trace(mVcdFile, fwork_q1, "(port)fwork_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_43_reg_249, "tmp_43_reg_249");
    sc_trace(mVcdFile, k_reg_259, "k_reg_259");
    sc_trace(mVcdFile, tmp_fu_306_p2, "tmp_fu_306_p2");
    sc_trace(mVcdFile, tmp_reg_546, "tmp_reg_546");
    sc_trace(mVcdFile, tmp_s_fu_312_p2, "tmp_s_fu_312_p2");
    sc_trace(mVcdFile, tmp_s_reg_550, "tmp_s_reg_550");
    sc_trace(mVcdFile, icmp_fu_329_p2, "icmp_fu_329_p2");
    sc_trace(mVcdFile, icmp_reg_555, "icmp_reg_555");
    sc_trace(mVcdFile, i_i_cast_fu_339_p1, "i_i_cast_fu_339_p1");
    sc_trace(mVcdFile, i_i_cast_reg_575, "i_i_cast_reg_575");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, indvar_flatten_next_fu_354_p2, "indvar_flatten_next_fu_354_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_586, "indvar_flatten_next_reg_586");
    sc_trace(mVcdFile, j_mid2_fu_365_p3, "j_mid2_fu_365_p3");
    sc_trace(mVcdFile, j_mid2_reg_591, "j_mid2_reg_591");
    sc_trace(mVcdFile, exitcond_flatten_fu_349_p2, "exitcond_flatten_fu_349_p2");
    sc_trace(mVcdFile, outrowidx_mid2_v_v_fu_380_p3, "outrowidx_mid2_v_v_fu_380_p3");
    sc_trace(mVcdFile, outrowidx_mid2_v_v_reg_596, "outrowidx_mid2_v_v_reg_596");
    sc_trace(mVcdFile, inneridx_mid2_fu_531_p2, "inneridx_mid2_fu_531_p2");
    sc_trace(mVcdFile, inneridx_mid2_reg_601, "inneridx_mid2_reg_601");
    sc_trace(mVcdFile, tmp_78_fu_392_p1, "tmp_78_fu_392_p1");
    sc_trace(mVcdFile, tmp_78_reg_606, "tmp_78_reg_606");
    sc_trace(mVcdFile, output_array_addr_reg_616, "output_array_addr_reg_616");
    sc_trace(mVcdFile, j_15_fu_419_p2, "j_15_fu_419_p2");
    sc_trace(mVcdFile, j_15_reg_624, "j_15_reg_624");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond_i_fu_413_p2, "exitcond_i_fu_413_p2");
    sc_trace(mVcdFile, output_array_addr_2_reg_634, "output_array_addr_2_reg_634");
    sc_trace(mVcdFile, i_s_fu_435_p2, "i_s_fu_435_p2");
    sc_trace(mVcdFile, outcols_reg_644, "outcols_reg_644");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_74_fu_448_p1, "tmp_74_fu_448_p1");
    sc_trace(mVcdFile, tmp_74_reg_649, "tmp_74_reg_649");
    sc_trace(mVcdFile, tmp_75_fu_452_p1, "tmp_75_fu_452_p1");
    sc_trace(mVcdFile, tmp_75_reg_654, "tmp_75_reg_654");
    sc_trace(mVcdFile, innerdim_reg_659, "innerdim_reg_659");
    sc_trace(mVcdFile, tmp_76_fu_456_p1, "tmp_76_fu_456_p1");
    sc_trace(mVcdFile, tmp_76_reg_664, "tmp_76_reg_664");
    sc_trace(mVcdFile, bound_fu_468_p2, "bound_fu_468_p2");
    sc_trace(mVcdFile, bound_reg_669, "bound_reg_669");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, exitcond_fu_474_p2, "exitcond_fu_474_p2");
    sc_trace(mVcdFile, exitcond_reg_679, "exitcond_reg_679");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter0, "ap_block_state8_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter1, "ap_block_state9_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, k_4_fu_479_p2, "k_4_fu_479_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, grp_fu_291_p2, "grp_fu_291_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, j_2_fu_518_p2, "j_2_fu_518_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state8, "ap_condition_pp0_exit_iter0_state8");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_ap_start, "grp_k2c_dot_1_fu_270_ap_start");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_ap_done, "grp_k2c_dot_1_fu_270_ap_done");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_ap_idle, "grp_k2c_dot_1_fu_270_ap_idle");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_ap_ready, "grp_k2c_dot_1_fu_270_ap_ready");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_C_array_address0, "grp_k2c_dot_1_fu_270_C_array_address0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_C_array_ce0, "grp_k2c_dot_1_fu_270_C_array_ce0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_C_array_we0, "grp_k2c_dot_1_fu_270_C_array_we0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_C_array_d0, "grp_k2c_dot_1_fu_270_C_array_d0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_Ar_array_address0, "grp_k2c_dot_1_fu_270_Ar_array_address0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_Ar_array_ce0, "grp_k2c_dot_1_fu_270_Ar_array_ce0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_Ar_shape_address0, "grp_k2c_dot_1_fu_270_Ar_shape_address0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_Ar_shape_ce0, "grp_k2c_dot_1_fu_270_Ar_shape_ce0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_B_array_address0, "grp_k2c_dot_1_fu_270_B_array_address0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_B_array_ce0, "grp_k2c_dot_1_fu_270_B_array_ce0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_B_shape_address0, "grp_k2c_dot_1_fu_270_B_shape_address0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_B_shape_ce0, "grp_k2c_dot_1_fu_270_B_shape_ce0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_fwork_address0, "grp_k2c_dot_1_fu_270_fwork_address0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_fwork_ce0, "grp_k2c_dot_1_fu_270_fwork_ce0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_fwork_we0, "grp_k2c_dot_1_fu_270_fwork_we0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_fwork_d0, "grp_k2c_dot_1_fu_270_fwork_d0");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_fwork_address1, "grp_k2c_dot_1_fu_270_fwork_address1");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_fwork_ce1, "grp_k2c_dot_1_fu_270_fwork_ce1");
    sc_trace(mVcdFile, i_i_reg_193, "i_i_reg_193");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, indvar_flatten_reg_205, "indvar_flatten_reg_205");
    sc_trace(mVcdFile, i_reg_216, "i_reg_216");
    sc_trace(mVcdFile, j_reg_227, "j_reg_227");
    sc_trace(mVcdFile, j_i_reg_238, "j_i_reg_238");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_i_fu_343_p2, "tmp_i_fu_343_p2");
    sc_trace(mVcdFile, grp_k2c_dot_1_fu_270_ap_start_reg, "grp_k2c_dot_1_fu_270_ap_start_reg");
    sc_trace(mVcdFile, tmp_44_cast_fu_400_p1, "tmp_44_cast_fu_400_p1");
    sc_trace(mVcdFile, j_i_cast1_fu_404_p1, "j_i_cast1_fu_404_p1");
    sc_trace(mVcdFile, tmp_i_cast_fu_430_p1, "tmp_i_cast_fu_430_p1");
    sc_trace(mVcdFile, tmp_46_cast_fu_498_p1, "tmp_46_cast_fu_498_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_48_cast_fu_513_p1, "tmp_48_cast_fu_513_p1");
    sc_trace(mVcdFile, grp_fu_291_p0, "grp_fu_291_p0");
    sc_trace(mVcdFile, grp_fu_291_p1, "grp_fu_291_p1");
    sc_trace(mVcdFile, tmp_47_fu_299_p2, "tmp_47_fu_299_p2");
    sc_trace(mVcdFile, tmp_73_fu_319_p4, "tmp_73_fu_319_p4");
    sc_trace(mVcdFile, i_i_cast7_fu_335_p1, "i_i_cast7_fu_335_p1");
    sc_trace(mVcdFile, exitcond16_fu_360_p2, "exitcond16_fu_360_p2");
    sc_trace(mVcdFile, i_41_fu_374_p2, "i_41_fu_374_p2");
    sc_trace(mVcdFile, grp_fu_523_p3, "grp_fu_523_p3");
    sc_trace(mVcdFile, j_i_cast_fu_409_p1, "j_i_cast_fu_409_p1");
    sc_trace(mVcdFile, tmp_i_43_fu_425_p2, "tmp_i_43_fu_425_p2");
    sc_trace(mVcdFile, outrows2_fu_441_p3, "outrows2_fu_441_p3");
    sc_trace(mVcdFile, bound_fu_468_p0, "bound_fu_468_p0");
    sc_trace(mVcdFile, bound_fu_468_p1, "bound_fu_468_p1");
    sc_trace(mVcdFile, tmp_81_fu_489_p1, "tmp_81_fu_489_p1");
    sc_trace(mVcdFile, tmp_44_fu_493_p2, "tmp_44_fu_493_p2");
    sc_trace(mVcdFile, tmp_80_fu_485_p1, "tmp_80_fu_485_p1");
    sc_trace(mVcdFile, tmp_45_fu_503_p2, "tmp_45_fu_503_p2");
    sc_trace(mVcdFile, tmp_46_fu_508_p2, "tmp_46_fu_508_p2");
    sc_trace(mVcdFile, tmp_77_fu_388_p1, "tmp_77_fu_388_p1");
    sc_trace(mVcdFile, grp_fu_523_p2, "grp_fu_523_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, bound_fu_468_p00, "bound_fu_468_p00");
    sc_trace(mVcdFile, bound_fu_468_p10, "bound_fu_468_p10");
#endif

    }
}

k2c_dense::~k2c_dense() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_k2c_dot_1_fu_270;
    delete face_classifier_cbkb_U30;
    delete face_classifier_ccud_U31;
    delete face_classifier_chbi_U32;
    delete face_classifier_cg8j_U33;
}

void k2c_dense::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state8.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state8.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state8.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_k2c_dot_1_fu_270_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_k2c_dot_1_fu_270_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_k2c_dot_1_fu_270_ap_ready.read())) {
            grp_k2c_dot_1_fu_270_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_413_p2.read(), ap_const_lv1_1))) {
        i_i_reg_193 = i_s_fu_435_p2.read();
    } else if ((esl_seteq<1,1,1>(grp_k2c_dot_1_fu_270_ap_done.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i_i_reg_193 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_reg_216 = outrowidx_mid2_v_v_reg_596.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_reg_216 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        indvar_flatten_reg_205 = indvar_flatten_next_reg_586.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten_reg_205 = ap_const_lv128_lc_1;
    }
    if ((esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_343_p2.read(), ap_const_lv1_1))) {
        j_i_reg_238 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_i_reg_238 = j_15_reg_624.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_reg_227 = j_2_fu_518_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_227 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_474_p2.read()))) {
        k_reg_259 = k_4_fu_479_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        k_reg_259 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_679.read()))) {
        tmp_43_reg_249 = grp_fu_291_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_43_reg_249 = bias_array_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        bound_reg_669 = bound_fu_468_p2.read();
        innerdim_reg_659 = kernel_shape_q1.read();
        outcols_reg_644 = kernel_shape_q0.read();
        tmp_74_reg_649 = tmp_74_fu_448_p1.read();
        tmp_75_reg_654 = tmp_75_fu_452_p1.read();
        tmp_76_reg_664 = tmp_76_fu_456_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_reg_679 = exitcond_fu_474_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_0))) {
        i_i_cast_reg_575 = i_i_cast_fu_339_p1.read();
    }
    if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        icmp_reg_555 = icmp_fu_329_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_1))) {
        indvar_flatten_next_reg_586 = indvar_flatten_next_fu_354_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten_fu_349_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        inneridx_mid2_reg_601 = inneridx_mid2_fu_531_p2.read();
        j_mid2_reg_591 = j_mid2_fu_365_p3.read();
        output_array_addr_reg_616 =  (sc_lv<12>) (tmp_44_cast_fu_400_p1.read());
        outrowidx_mid2_v_v_reg_596 = outrowidx_mid2_v_v_fu_380_p3.read();
        tmp_78_reg_606 = tmp_78_fu_392_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_15_reg_624 = j_15_fu_419_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_i_fu_413_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        output_array_addr_2_reg_634 =  (sc_lv<12>) (tmp_i_cast_fu_430_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_reg_546 = tmp_fu_306_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_s_reg_550 = tmp_s_fu_312_p2.read();
    }
}

void k2c_dense::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[7];
}

void k2c_dense::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void k2c_dense::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[8];
}

void k2c_dense::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void k2c_dense::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void k2c_dense::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void k2c_dense::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void k2c_dense::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void k2c_dense::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void k2c_dense::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_dense::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_dense::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_dense::thread_ap_block_state8_pp0_stage0_iter0() {
    ap_block_state8_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_dense::thread_ap_block_state9_pp0_stage0_iter1() {
    ap_block_state9_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_dense::thread_ap_condition_pp0_exit_iter0_state8() {
    if (esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state8 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state8 = ap_const_logic_0;
    }
}

void k2c_dense::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          ((esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_1) && 
            esl_seteq<1,1,1>(exitcond_flatten_fu_349_p2.read(), ap_const_lv1_1)) || 
           (esl_seteq<1,1,1>(tmp_i_fu_343_p2.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_0)))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void k2c_dense::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void k2c_dense::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void k2c_dense::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         ((esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(exitcond_flatten_fu_349_p2.read(), ap_const_lv1_1)) || 
          (esl_seteq<1,1,1>(tmp_i_fu_343_p2.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_0))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void k2c_dense::thread_bias_array_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        bias_array_address0 =  (sc_lv<12>) (j_i_cast1_fu_404_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        bias_array_address0 =  (sc_lv<12>) (j_mid2_fu_365_p3.read());
    } else {
        bias_array_address0 = "XXXXXXXXXXXX";
    }
}

void k2c_dense::thread_bias_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        bias_array_ce0 = ap_const_logic_1;
    } else {
        bias_array_ce0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_bound_fu_468_p0() {
    bound_fu_468_p0 =  (sc_lv<64>) (bound_fu_468_p00.read());
}

void k2c_dense::thread_bound_fu_468_p00() {
    bound_fu_468_p00 = esl_zext<128,64>(kernel_shape_q0.read());
}

void k2c_dense::thread_bound_fu_468_p1() {
    bound_fu_468_p1 =  (sc_lv<64>) (bound_fu_468_p10.read());
}

void k2c_dense::thread_bound_fu_468_p10() {
    bound_fu_468_p10 = esl_zext<128,64>(outrows2_fu_441_p3.read());
}

void k2c_dense::thread_bound_fu_468_p2() {
    bound_fu_468_p2 = (!bound_fu_468_p0.read().is_01() || !bound_fu_468_p1.read().is_01())? sc_lv<128>(): sc_biguint<64>(bound_fu_468_p0.read()) * sc_biguint<64>(bound_fu_468_p1.read());
}

void k2c_dense::thread_exitcond16_fu_360_p2() {
    exitcond16_fu_360_p2 = (!j_reg_227.read().is_01() || !outcols_reg_644.read().is_01())? sc_lv<1>(): sc_lv<1>(j_reg_227.read() == outcols_reg_644.read());
}

void k2c_dense::thread_exitcond_flatten_fu_349_p2() {
    exitcond_flatten_fu_349_p2 = (!indvar_flatten_reg_205.read().is_01() || !bound_reg_669.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_205.read() == bound_reg_669.read());
}

void k2c_dense::thread_exitcond_fu_474_p2() {
    exitcond_fu_474_p2 = (!k_reg_259.read().is_01() || !innerdim_reg_659.read().is_01())? sc_lv<1>(): sc_lv<1>(k_reg_259.read() == innerdim_reg_659.read());
}

void k2c_dense::thread_exitcond_i_fu_413_p2() {
    exitcond_i_fu_413_p2 = (!j_i_reg_238.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_238.read() == ap_const_lv7_64);
}

void k2c_dense::thread_fwork_address0() {
    fwork_address0 = grp_k2c_dot_1_fu_270_fwork_address0.read();
}

void k2c_dense::thread_fwork_address1() {
    fwork_address1 = grp_k2c_dot_1_fu_270_fwork_address1.read();
}

void k2c_dense::thread_fwork_ce0() {
    fwork_ce0 = grp_k2c_dot_1_fu_270_fwork_ce0.read();
}

void k2c_dense::thread_fwork_ce1() {
    fwork_ce1 = grp_k2c_dot_1_fu_270_fwork_ce1.read();
}

void k2c_dense::thread_fwork_d0() {
    fwork_d0 = grp_k2c_dot_1_fu_270_fwork_d0.read();
}

void k2c_dense::thread_fwork_we0() {
    fwork_we0 = grp_k2c_dot_1_fu_270_fwork_we0.read();
}

void k2c_dense::thread_grp_fu_291_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_291_p0 = tmp_43_reg_249.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_291_p0 = output_array_q0.read();
    } else {
        grp_fu_291_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_dense::thread_grp_fu_291_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_291_p1 = tmp_47_fu_299_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_291_p1 = bias_array_q0.read();
    } else {
        grp_fu_291_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_dense::thread_grp_fu_523_p2() {
    grp_fu_523_p2 = j_mid2_fu_365_p3.read().range(13-1, 0);
}

void k2c_dense::thread_grp_k2c_dot_1_fu_270_ap_start() {
    grp_k2c_dot_1_fu_270_ap_start = grp_k2c_dot_1_fu_270_ap_start_reg.read();
}

void k2c_dense::thread_i_41_fu_374_p2() {
    i_41_fu_374_p2 = (!ap_const_lv64_1.is_01() || !i_reg_216.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(i_reg_216.read()));
}

void k2c_dense::thread_i_i_cast7_fu_335_p1() {
    i_i_cast7_fu_335_p1 = esl_sext<7,6>(i_i_reg_193.read());
}

void k2c_dense::thread_i_i_cast_fu_339_p1() {
    i_i_cast_fu_339_p1 = esl_zext<8,7>(i_i_cast7_fu_335_p1.read());
}

void k2c_dense::thread_i_s_fu_435_p2() {
    i_s_fu_435_p2 = (!i_i_reg_193.read().is_01() || !ap_const_lv6_24.is_01())? sc_lv<6>(): (sc_bigint<6>(i_i_reg_193.read()) + sc_bigint<6>(ap_const_lv6_24));
}

void k2c_dense::thread_icmp_fu_329_p2() {
    icmp_fu_329_p2 = (!tmp_73_fu_319_p4.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_73_fu_319_p4.read() != ap_const_lv63_0);
}

void k2c_dense::thread_indvar_flatten_next_fu_354_p2() {
    indvar_flatten_next_fu_354_p2 = (!indvar_flatten_reg_205.read().is_01() || !ap_const_lv128_lc_2.is_01())? sc_lv<128>(): (sc_biguint<128>(indvar_flatten_reg_205.read()) + sc_biguint<128>(ap_const_lv128_lc_2));
}

void k2c_dense::thread_input_array_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        input_array_address0 =  (sc_lv<12>) (tmp_46_cast_fu_498_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_array_address0 = grp_k2c_dot_1_fu_270_Ar_array_address0.read();
    } else {
        input_array_address0 = "XXXXXXXXXXXX";
    }
}

void k2c_dense::thread_input_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        input_array_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_array_ce0 = grp_k2c_dot_1_fu_270_Ar_array_ce0.read();
    } else {
        input_array_ce0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_input_shape_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1))) {
        input_shape_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_shape_address0 = grp_k2c_dot_1_fu_270_Ar_shape_address0.read();
    } else {
        input_shape_address0 =  (sc_lv<3>) ("XXX");
    }
}

void k2c_dense::thread_input_shape_ce0() {
    if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        input_shape_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_shape_ce0 = grp_k2c_dot_1_fu_270_Ar_shape_ce0.read();
    } else {
        input_shape_ce0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_j_15_fu_419_p2() {
    j_15_fu_419_p2 = (!j_i_reg_238.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_i_reg_238.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void k2c_dense::thread_j_2_fu_518_p2() {
    j_2_fu_518_p2 = (!j_mid2_reg_591.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(j_mid2_reg_591.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void k2c_dense::thread_j_i_cast1_fu_404_p1() {
    j_i_cast1_fu_404_p1 = esl_zext<64,7>(j_i_reg_238.read());
}

void k2c_dense::thread_j_i_cast_fu_409_p1() {
    j_i_cast_fu_409_p1 = esl_zext<8,7>(j_i_reg_238.read());
}

void k2c_dense::thread_j_mid2_fu_365_p3() {
    j_mid2_fu_365_p3 = (!exitcond16_fu_360_p2.read()[0].is_01())? sc_lv<64>(): ((exitcond16_fu_360_p2.read()[0].to_bool())? ap_const_lv64_0: j_reg_227.read());
}

void k2c_dense::thread_k_4_fu_479_p2() {
    k_4_fu_479_p2 = (!k_reg_259.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(k_reg_259.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void k2c_dense::thread_kernel_array_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        kernel_array_address0 =  (sc_lv<19>) (tmp_48_cast_fu_513_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        kernel_array_address0 = grp_k2c_dot_1_fu_270_B_array_address0.read();
    } else {
        kernel_array_address0 =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_dense::thread_kernel_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        kernel_array_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        kernel_array_ce0 = grp_k2c_dot_1_fu_270_B_array_ce0.read();
    } else {
        kernel_array_ce0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_kernel_shape_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1))) {
        kernel_shape_address0 =  (sc_lv<3>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        kernel_shape_address0 = grp_k2c_dot_1_fu_270_B_shape_address0.read();
    } else {
        kernel_shape_address0 =  (sc_lv<3>) ("XXX");
    }
}

void k2c_dense::thread_kernel_shape_address1() {
    kernel_shape_address1 =  (sc_lv<3>) (ap_const_lv64_0);
}

void k2c_dense::thread_kernel_shape_ce0() {
    if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        kernel_shape_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        kernel_shape_ce0 = grp_k2c_dot_1_fu_270_B_shape_ce0.read();
    } else {
        kernel_shape_ce0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_kernel_shape_ce1() {
    if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        kernel_shape_ce1 = ap_const_logic_1;
    } else {
        kernel_shape_ce1 = ap_const_logic_0;
    }
}

void k2c_dense::thread_output_array_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)))) {
        output_array_address0 = output_array_addr_reg_616.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_array_address0 = output_array_addr_2_reg_634.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_array_address0 =  (sc_lv<12>) (tmp_i_cast_fu_430_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_array_address0 = grp_k2c_dot_1_fu_270_C_array_address0.read();
    } else {
        output_array_address0 = "XXXXXXXXXXXX";
    }
}

void k2c_dense::thread_output_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        output_array_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_array_ce0 = grp_k2c_dot_1_fu_270_C_array_ce0.read();
    } else {
        output_array_ce0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_output_array_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_array_d0 = bias_array_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)))) {
        output_array_d0 = grp_fu_291_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_array_d0 = grp_k2c_dot_1_fu_270_C_array_d0.read();
    } else {
        output_array_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_dense::thread_output_array_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_679.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        output_array_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_array_we0 = grp_k2c_dot_1_fu_270_C_array_we0.read();
    } else {
        output_array_we0 = ap_const_logic_0;
    }
}

void k2c_dense::thread_outrowidx_mid2_v_v_fu_380_p3() {
    outrowidx_mid2_v_v_fu_380_p3 = (!exitcond16_fu_360_p2.read()[0].is_01())? sc_lv<64>(): ((exitcond16_fu_360_p2.read()[0].to_bool())? i_41_fu_374_p2.read(): i_reg_216.read());
}

void k2c_dense::thread_outrows2_fu_441_p3() {
    outrows2_fu_441_p3 = (!icmp_reg_555.read()[0].is_01())? sc_lv<64>(): ((icmp_reg_555.read()[0].to_bool())? input_shape_q0.read(): ap_const_lv64_1);
}

void k2c_dense::thread_tmp_44_cast_fu_400_p1() {
    tmp_44_cast_fu_400_p1 = esl_zext<64,13>(grp_fu_523_p3.read());
}

void k2c_dense::thread_tmp_44_fu_493_p2() {
    tmp_44_fu_493_p2 = (!tmp_81_fu_489_p1.read().is_01() || !inneridx_mid2_reg_601.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_81_fu_489_p1.read()) + sc_bigint<13>(inneridx_mid2_reg_601.read()));
}

void k2c_dense::thread_tmp_45_fu_503_p2() {
    tmp_45_fu_503_p2 = (!tmp_74_reg_649.read().is_01() || !tmp_80_fu_485_p1.read().is_01())? sc_lv<20>(): sc_bigint<20>(tmp_74_reg_649.read()) * sc_bigint<20>(tmp_80_fu_485_p1.read());
}

void k2c_dense::thread_tmp_46_cast_fu_498_p1() {
    tmp_46_cast_fu_498_p1 = esl_zext<64,13>(tmp_44_fu_493_p2.read());
}

void k2c_dense::thread_tmp_46_fu_508_p2() {
    tmp_46_fu_508_p2 = (!tmp_45_fu_503_p2.read().is_01() || !tmp_78_reg_606.read().is_01())? sc_lv<20>(): (sc_biguint<20>(tmp_45_fu_503_p2.read()) + sc_biguint<20>(tmp_78_reg_606.read()));
}

void k2c_dense::thread_tmp_48_cast_fu_513_p1() {
    tmp_48_cast_fu_513_p1 = esl_zext<64,20>(tmp_46_fu_508_p2.read());
}

void k2c_dense::thread_tmp_73_fu_319_p4() {
    tmp_73_fu_319_p4 = input_ndim_read.read().range(63, 1);
}

void k2c_dense::thread_tmp_74_fu_448_p1() {
    tmp_74_fu_448_p1 = kernel_shape_q0.read().range(20-1, 0);
}

void k2c_dense::thread_tmp_75_fu_452_p1() {
    tmp_75_fu_452_p1 = kernel_shape_q0.read().range(13-1, 0);
}

void k2c_dense::thread_tmp_76_fu_456_p1() {
    tmp_76_fu_456_p1 = kernel_shape_q1.read().range(13-1, 0);
}

void k2c_dense::thread_tmp_77_fu_388_p1() {
    tmp_77_fu_388_p1 = outrowidx_mid2_v_v_fu_380_p3.read().range(13-1, 0);
}

void k2c_dense::thread_tmp_78_fu_392_p1() {
    tmp_78_fu_392_p1 = j_mid2_fu_365_p3.read().range(20-1, 0);
}

void k2c_dense::thread_tmp_80_fu_485_p1() {
    tmp_80_fu_485_p1 = k_reg_259.read().range(20-1, 0);
}

void k2c_dense::thread_tmp_81_fu_489_p1() {
    tmp_81_fu_489_p1 = k_reg_259.read().range(13-1, 0);
}

void k2c_dense::thread_tmp_fu_306_p2() {
    tmp_fu_306_p2 = (!input_ndim_read.read().is_01() || !ap_const_lv64_3.is_01())? sc_lv<1>(): (sc_biguint<64>(input_ndim_read.read()) < sc_biguint<64>(ap_const_lv64_3));
}

void k2c_dense::thread_tmp_i_43_fu_425_p2() {
    tmp_i_43_fu_425_p2 = (!j_i_cast_fu_409_p1.read().is_01() || !i_i_cast_reg_575.read().is_01())? sc_lv<8>(): (sc_biguint<8>(j_i_cast_fu_409_p1.read()) + sc_biguint<8>(i_i_cast_reg_575.read()));
}

void k2c_dense::thread_tmp_i_cast_fu_430_p1() {
    tmp_i_cast_fu_430_p1 = esl_zext<64,8>(tmp_i_43_fu_425_p2.read());
}

void k2c_dense::thread_tmp_i_fu_343_p2() {
    tmp_i_fu_343_p2 = (!i_i_reg_193.read().is_01() || !ap_const_lv6_24.is_01())? sc_lv<1>(): (sc_biguint<6>(i_i_reg_193.read()) < sc_biguint<6>(ap_const_lv6_24));
}

void k2c_dense::thread_tmp_s_fu_312_p2() {
    tmp_s_fu_312_p2 = (!input_ndim_read.read().is_01() || !ap_const_lv64_FFFFFFFFFFFFFFFF.is_01())? sc_lv<64>(): (sc_biguint<64>(input_ndim_read.read()) + sc_bigint<64>(ap_const_lv64_FFFFFFFFFFFFFFFF));
}

void k2c_dense::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else if ((esl_seteq<1,1,1>(tmp_fu_306_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(grp_k2c_dot_1_fu_270_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && ((esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(exitcond_flatten_fu_349_p2.read(), ap_const_lv1_1)) || 
  (esl_seteq<1,1,1>(tmp_i_fu_343_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_0))))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(exitcond_flatten_fu_349_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_reg_546.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond_i_fu_413_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 128 : 
            if (!(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_fu_474_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

