// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module face_classifier_c_dense_input_input_array_if (
    // system singals
    input  wire        clk,
    input  wire        reset,
    // user signals
    input  wire [18:0] dense_input_input_array_address0,
    input  wire        dense_input_input_array_ce0,
    output wire [31:0] dense_input_input_array_q0,
    // bus signals
    output wire        Clk_A,
    output wire        Rst_A,
    output wire        EN_A,
    output wire [3:0]  WEN_A,
    output wire [31:0] Addr_A,
    output wire [31:0] Dout_A,
    input  wire [31:0] Din_A
);
//------------------------Body---------------------------
assign Clk_A                      = clk;
assign Rst_A                      = reset;
assign EN_A                       = dense_input_input_array_ce0;
assign Addr_A                     = {dense_input_input_array_address0, 2'b0};
assign WEN_A                      = 4'b0;
assign Dout_A                     = 32'b0;
assign dense_input_input_array_q0 = Din_A[31:0];

endmodule
