// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_HH_
#define _dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_mul_mul_9s_11s_25_1_1.h"
#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_w6_V.h"
#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V.h"
#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_mult_V.h"
#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_acc_V.h"

namespace ap_rtl {

struct dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<7> > data_V_address0;
    sc_out< sc_logic > data_V_ce0;
    sc_in< sc_lv<11> > data_V_q0;
    sc_out< sc_lv<4> > res_V_address0;
    sc_out< sc_logic > res_V_ce0;
    sc_out< sc_logic > res_V_we0;
    sc_out< sc_lv<16> > res_V_d0;


    // Module declarations
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s(sc_module_name name);
    SC_HAS_PROCESS(dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s);

    ~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s();

    sc_trace_file* mVcdFile;

    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_w6_V* w6_V_U;
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V* b6_V_U;
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_mult_V* mult_V_U;
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_acc_V* acc_V_U;
    myproject_mul_mul_9s_11s_25_1_1<1,1,9,11,25>* myproject_mul_mul_9s_11s_25_1_1_U12;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<10> > w6_V_address0;
    sc_signal< sc_logic > w6_V_ce0;
    sc_signal< sc_lv<9> > w6_V_q0;
    sc_signal< sc_lv<4> > b6_V_address0;
    sc_signal< sc_logic > b6_V_ce0;
    sc_signal< sc_lv<8> > b6_V_q0;
    sc_signal< sc_lv<7> > ii_1_fu_241_p2;
    sc_signal< sc_lv<7> > ii_1_reg_448;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_fu_235_p2;
    sc_signal< sc_lv<10> > p_shl_fu_252_p3;
    sc_signal< sc_lv<10> > p_shl_reg_458;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<8> > p_shl7_fu_260_p3;
    sc_signal< sc_lv<8> > p_shl7_reg_463;
    sc_signal< sc_lv<25> > OP1_V_cast_cast_fu_268_p1;
    sc_signal< sc_lv<25> > OP1_V_cast_cast_reg_468;
    sc_signal< sc_lv<4> > jj_1_fu_282_p2;
    sc_signal< sc_lv<4> > jj_1_reg_476;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > tmp_9_fu_302_p1;
    sc_signal< sc_lv<64> > tmp_9_reg_481;
    sc_signal< sc_lv<1> > tmp_6_fu_276_p2;
    sc_signal< sc_lv<4> > iacc_1_fu_331_p2;
    sc_signal< sc_lv<4> > iacc_1_reg_494;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > tmp_5_fu_337_p1;
    sc_signal< sc_lv<64> > tmp_5_reg_499;
    sc_signal< sc_lv<1> > tmp_2_fu_325_p2;
    sc_signal< sc_lv<7> > ii_2_fu_353_p2;
    sc_signal< sc_lv<7> > ii_2_reg_512;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<10> > p_shl8_fu_359_p3;
    sc_signal< sc_lv<10> > p_shl8_reg_517;
    sc_signal< sc_lv<1> > tmp_4_fu_347_p2;
    sc_signal< sc_lv<8> > p_shl9_fu_367_p3;
    sc_signal< sc_lv<8> > p_shl9_reg_522;
    sc_signal< sc_lv<4> > jj_2_fu_385_p2;
    sc_signal< sc_lv<4> > jj_2_reg_530;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<4> > acc_V_addr_2_reg_535;
    sc_signal< sc_lv<1> > tmp_13_fu_379_p2;
    sc_signal< sc_lv<4> > ires_1_fu_428_p2;
    sc_signal< sc_lv<4> > ires_1_reg_548;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > tmp_12_fu_434_p1;
    sc_signal< sc_lv<64> > tmp_12_reg_553;
    sc_signal< sc_lv<1> > tmp_7_fu_422_p2;
    sc_signal< sc_lv<10> > mult_V_address0;
    sc_signal< sc_logic > mult_V_ce0;
    sc_signal< sc_logic > mult_V_we0;
    sc_signal< sc_lv<16> > mult_V_d0;
    sc_signal< sc_lv<16> > mult_V_q0;
    sc_signal< sc_lv<4> > acc_V_address0;
    sc_signal< sc_logic > acc_V_ce0;
    sc_signal< sc_logic > acc_V_we0;
    sc_signal< sc_lv<16> > acc_V_d0;
    sc_signal< sc_lv<16> > acc_V_q0;
    sc_signal< sc_lv<7> > ii_reg_168;
    sc_signal< sc_lv<4> > jj_reg_180;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > iacc_reg_191;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<7> > ii2_reg_202;
    sc_signal< sc_lv<4> > jj3_reg_213;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<4> > ires_reg_224;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > tmp_s_fu_247_p1;
    sc_signal< sc_lv<64> > tmp_14_fu_405_p1;
    sc_signal< sc_lv<64> > tmp_15_fu_410_p1;
    sc_signal< sc_lv<16> > b6_V_load_cast_fu_342_p1;
    sc_signal< sc_lv<16> > p_Val2_s_35_fu_415_p2;
    sc_signal< sc_lv<8> > jj_cast8_fu_272_p1;
    sc_signal< sc_lv<8> > tmp1_fu_288_p2;
    sc_signal< sc_lv<10> > tmp1_cast_fu_293_p1;
    sc_signal< sc_lv<10> > index_fu_297_p2;
    sc_signal< sc_lv<25> > p_Val2_s_fu_439_p2;
    sc_signal< sc_lv<15> > tmp_766_fu_311_p4;
    sc_signal< sc_lv<8> > jj3_cast5_fu_375_p1;
    sc_signal< sc_lv<8> > tmp2_fu_391_p2;
    sc_signal< sc_lv<10> > tmp2_cast_fu_396_p1;
    sc_signal< sc_lv<10> > index_1_fu_400_p2;
    sc_signal< sc_lv<11> > p_Val2_s_fu_439_p1;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_state11;
    static const sc_lv<12> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<7> ap_const_lv7_64;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_18;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_OP1_V_cast_cast_fu_268_p1();
    void thread_acc_V_address0();
    void thread_acc_V_ce0();
    void thread_acc_V_d0();
    void thread_acc_V_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_b6_V_address0();
    void thread_b6_V_ce0();
    void thread_b6_V_load_cast_fu_342_p1();
    void thread_data_V_address0();
    void thread_data_V_ce0();
    void thread_iacc_1_fu_331_p2();
    void thread_ii_1_fu_241_p2();
    void thread_ii_2_fu_353_p2();
    void thread_index_1_fu_400_p2();
    void thread_index_fu_297_p2();
    void thread_ires_1_fu_428_p2();
    void thread_jj3_cast5_fu_375_p1();
    void thread_jj_1_fu_282_p2();
    void thread_jj_2_fu_385_p2();
    void thread_jj_cast8_fu_272_p1();
    void thread_mult_V_address0();
    void thread_mult_V_ce0();
    void thread_mult_V_d0();
    void thread_mult_V_we0();
    void thread_p_Val2_s_35_fu_415_p2();
    void thread_p_Val2_s_fu_439_p1();
    void thread_p_shl7_fu_260_p3();
    void thread_p_shl8_fu_359_p3();
    void thread_p_shl9_fu_367_p3();
    void thread_p_shl_fu_252_p3();
    void thread_res_V_address0();
    void thread_res_V_ce0();
    void thread_res_V_d0();
    void thread_res_V_we0();
    void thread_tmp1_cast_fu_293_p1();
    void thread_tmp1_fu_288_p2();
    void thread_tmp2_cast_fu_396_p1();
    void thread_tmp2_fu_391_p2();
    void thread_tmp_12_fu_434_p1();
    void thread_tmp_13_fu_379_p2();
    void thread_tmp_14_fu_405_p1();
    void thread_tmp_15_fu_410_p1();
    void thread_tmp_2_fu_325_p2();
    void thread_tmp_4_fu_347_p2();
    void thread_tmp_5_fu_337_p1();
    void thread_tmp_6_fu_276_p2();
    void thread_tmp_766_fu_311_p4();
    void thread_tmp_7_fu_422_p2();
    void thread_tmp_9_fu_302_p1();
    void thread_tmp_fu_235_p2();
    void thread_tmp_s_fu_247_p1();
    void thread_w6_V_address0();
    void thread_w6_V_ce0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
